/**
 * Automation Deployer
 * ────────────────────
 * Takes generated Business Builder assets and deploys them to the live services:
 *   - Mautic: email sequences, lead magnets, cold outbound campaigns
 *   - WordPress: home page copy, pricing page, legal docs, SEO posts (drafts)
 *   - SuiteCRM: canned responses, support workflows
 *
 * All deployments are non-blocking and fail gracefully — the asset is marked
 * with deployedTo + deployedAt on success, errorMessage on failure.
 */

import { getDb } from "./db";
import { generatedAssets } from "../drizzle/schema";
import { and, eq } from "drizzle-orm";

// ─── Service Config (read from env, set on Vultr) ─────────────────────────────

function getMauticConfig() {
  return {
    baseUrl: process.env.MAUTIC_URL || "http://localhost:8082",
    user: process.env.MAUTIC_USER || "admin",
    password: process.env.MAUTIC_PASSWORD || "",
  };
}

function getWordPressConfig() {
  return {
    baseUrl: process.env.WORDPRESS_URL || "http://localhost:8080",
    user: process.env.WORDPRESS_USER || "admin",
    password: process.env.WORDPRESS_PASSWORD || "",
  };
}

function getSuiteCRMConfig() {
  return {
    baseUrl: process.env.SUITECRM_URL || "http://localhost:8083",
    user: process.env.SUITECRM_USER || "admin",
    password: process.env.SUITECRM_PASSWORD || "",
  };
}

// ─── Mautic Deployer ──────────────────────────────────────────────────────────

/**
 * Parse email sequences from generated content.
 * Expects sections like: ## Email 1\n**Subject:** ...\n**Body:** ...
 */
function parseEmailSequences(content: string): Array<{
  subject: string;
  previewText: string;
  body: string;
  order: number;
}> {
  const emails: Array<{ subject: string; previewText: string; body: string; order: number }> = [];
  const emailBlocks = content.split(/##\s+Email\s+\d+/i).filter(Boolean);

  emailBlocks.forEach((block, index) => {
    const subjectMatch = block.match(/\*\*Subject[:\s]+\*\*\s*(.+)/i) ||
      block.match(/Subject[:\s]+(.+)/i);
    const previewMatch = block.match(/\*\*Preview[:\s]+\*\*\s*(.+)/i) ||
      block.match(/Preview[:\s]+(.+)/i);

    if (subjectMatch) {
      emails.push({
        subject: subjectMatch[1].trim(),
        previewText: previewMatch ? previewMatch[1].trim() : "",
        body: block.replace(/\*\*Subject[^*]*\*\*[^\n]*/gi, "")
          .replace(/\*\*Preview[^*]*\*\*[^\n]*/gi, "")
          .trim(),
        order: index + 1,
      });
    }
  });

  return emails;
}

async function deployToMautic(
  promptId: string,
  content: string,
  campaignName: string
): Promise<{ success: boolean; detail: string }> {
  const config = getMauticConfig();

  try {
    const auth = Buffer.from(`${config.user}:${config.password}`).toString("base64");
    const headers = {
      "Authorization": `Basic ${auth}`,
      "Content-Type": "application/json",
    };

    // Create email campaign
    const campaignRes = await fetch(`${config.baseUrl}/api/campaigns/new`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: campaignName,
        description: `Auto-generated by LaunchOps Business Builder — ${promptId}`,
        isPublished: false,
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (!campaignRes.ok) {
      return {
        success: false,
        detail: `Mautic campaign creation failed: ${campaignRes.status}`,
      };
    }

    const campaign = await campaignRes.json() as { campaign?: { id: number } };
    const campaignId = campaign?.campaign?.id;

    // Parse and create individual emails
    const emails = parseEmailSequences(content);
    let createdCount = 0;

    for (const email of emails) {
      const emailRes = await fetch(`${config.baseUrl}/api/emails/new`, {
        method: "POST",
        headers,
        body: JSON.stringify({
          name: `${campaignName} — Email ${email.order}`,
          subject: email.subject,
          previewText: email.previewText,
          customHtml: `<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">${email.body.replace(/\n/g, "<br>")}</div>`,
          emailType: "list",
          isPublished: false,
          campaign: campaignId ? { id: campaignId } : undefined,
        }),
        signal: AbortSignal.timeout(10000),
      });

      if (emailRes.ok) createdCount++;
    }

    return {
      success: true,
      detail: `Created Mautic campaign with ${createdCount} emails`,
    };
  } catch (err: any) {
    return {
      success: false,
      detail: `Mautic deploy error: ${err?.message || "Unknown error"}`,
    };
  }
}

// ─── WordPress Deployer ───────────────────────────────────────────────────────

async function deployToWordPress(
  promptId: string,
  content: string,
  pageTitle: string,
  pageType: "page" | "post" = "page"
): Promise<{ success: boolean; detail: string }> {
  const config = getWordPressConfig();

  try {
    const auth = Buffer.from(`${config.user}:${config.password}`).toString("base64");

    const endpoint = pageType === "post"
      ? `${config.baseUrl}/wp-json/wp/v2/posts`
      : `${config.baseUrl}/wp-json/wp/v2/pages`;

    const res = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Authorization": `Basic ${auth}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: pageTitle,
        content: content,
        status: "draft", // Always draft — human reviews before publishing
        meta: {
          _launchops_generated: true,
          _launchops_prompt_id: promptId,
          _launchops_generated_at: new Date().toISOString(),
        },
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (!res.ok) {
      const body = await res.text();
      return {
        success: false,
        detail: `WordPress deploy failed: ${res.status} — ${body.slice(0, 200)}`,
      };
    }

    const post = await res.json() as { id: number; link: string };
    return {
      success: true,
      detail: `Created WordPress draft (ID: ${post.id}) — review at ${config.baseUrl}/wp-admin`,
    };
  } catch (err: any) {
    return {
      success: false,
      detail: `WordPress deploy error: ${err?.message || "Unknown error"}`,
    };
  }
}

// ─── SuiteCRM Deployer ────────────────────────────────────────────────────────

/**
 * Parse canned responses from generated content.
 * Expects sections like: ## Response 1: [Title]\n[Body]
 */
function parseCannedResponses(content: string): Array<{ title: string; body: string }> {
  const responses: Array<{ title: string; body: string }> = [];
  const blocks = content.split(/##\s+(?:Response|Canned Response)\s+\d+/i).filter(Boolean);

  blocks.forEach((block) => {
    const titleMatch = block.match(/^[:\s]*([^\n]+)/);
    if (titleMatch) {
      responses.push({
        title: titleMatch[1].trim().replace(/^[:\s]+/, ""),
        body: block.replace(/^[^\n]+\n/, "").trim(),
      });
    }
  });

  return responses;
}

async function deployToSuiteCRM(
  promptId: string,
  content: string
): Promise<{ success: boolean; detail: string }> {
  const config = getSuiteCRMConfig();

  try {
    // SuiteCRM uses a legacy V8 API — we'll use the REST v8 endpoint
    const loginRes = await fetch(`${config.baseUrl}/api/v8/login`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        username: config.user,
        password: config.password,
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (!loginRes.ok) {
      return {
        success: false,
        detail: `SuiteCRM login failed: ${loginRes.status}`,
      };
    }

    const loginData = await loginRes.json() as { token?: string };
    const token = loginData?.token;
    if (!token) {
      return { success: false, detail: "SuiteCRM: no auth token returned" };
    }

    const responses = parseCannedResponses(content);
    let createdCount = 0;

    for (const resp of responses) {
      const createRes = await fetch(`${config.baseUrl}/api/v8/module/AOS_PDF_Templates`, {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          data: {
            type: "AOS_PDF_Templates",
            attributes: {
              name: resp.title,
              body: resp.body,
              description: `Auto-generated by LaunchOps Business Builder — ${promptId}`,
            },
          },
        }),
        signal: AbortSignal.timeout(10000),
      });

      if (createRes.ok) createdCount++;
    }

    return {
      success: true,
      detail: `Created ${createdCount} canned responses in SuiteCRM`,
    };
  } catch (err: any) {
    return {
      success: false,
      detail: `SuiteCRM deploy error: ${err?.message || "Unknown error"}`,
    };
  }
}

// ─── Main Deployer ────────────────────────────────────────────────────────────

export interface DeployResult {
  success: boolean;
  deployedTo: string;
  detail: string;
}

export async function deployAsset(
  runId: string,
  promptId: string,
  content: string,
  deployTarget: "mautic" | "wordpress" | "suitecrm" | "none"
): Promise<DeployResult> {
  if (deployTarget === "none") {
    return { success: true, deployedTo: "none", detail: "No deployment target" };
  }

  let result: { success: boolean; detail: string };

  switch (deployTarget) {
    case "mautic":
      result = await deployToMautic(
        promptId,
        content,
        `LaunchOps — ${promptId.replace(/_/g, " ").replace(/prompt \d+ /i, "")}`
      );
      break;

    case "wordpress":
      result = await deployToWordPress(
        promptId,
        content,
        promptId.includes("seo") || promptId.includes("content")
          ? `[DRAFT] SEO Post — ${new Date().toLocaleDateString()}`
          : `[DRAFT] ${promptId.replace(/_/g, " ").replace(/prompt \d+ /i, "")}`,
        promptId.includes("seo") ? "post" : "page"
      );
      break;

    case "suitecrm":
      result = await deployToSuiteCRM(promptId, content);
      break;

    default:
      result = { success: false, detail: `Unknown deploy target: ${deployTarget}` };
  }

  // Update asset record
  const db = await getDb();
  if (db) {
    await db
      .update(generatedAssets)
      .set({
        deployedTo: deployTarget,
        deployedAt: result.success ? new Date() : undefined,
        errorMessage: result.success ? undefined : result.detail,
        updatedAt: new Date(),
      })
      .where(
        and(
          eq(generatedAssets.runId, runId),
          eq(generatedAssets.promptId, promptId)
        )
      );
  }

  return { ...result, deployedTo: deployTarget };
}
